//
//  phrases.h
//  lampbox
//
// Copyright (C) 2021 Michael Budiansky. All rights reserved.
//

#ifndef phrases_h
#define phrases_h

enum PhraseID {
    UNKNOWN = -1,
    COMPUTER_,
    YES_,
    NO_,
    DOWN_,
    BLINKY_,
    RED_LIGHT_,
    RED__LIGHT_,
    GREEN_LIGHT_,
    GREEN__LIGHT_,
    BLUE_LIGHT_,
    BLUE__LIGHT_,
    YELLOW_LIGHT_,
    YELLOW__LIGHT_,
    ORANGE_LIGHT_,
    ORANGE__LIGHT_,
    PURPLE_LIGHT_,
    PURPLE__LIGHT_,
    MAROON_LIGHT_,
    MAROON__LIGHT_,
    LAMP_OFF_,
    LAMP__OFF_,
    OKAY_,
    REPEAT_AFTER_ME_,
    REPEAT__AFTER__ME_,
    CHANGE_VOICE_,
    ALEXA_,
    HEY_SIRI_,
    HEY__SIRI_,
    HEY_GOOGLE_,
    HEY__GOOGLE_,
    EXIT_PROGRAM_,
    SHUT_DOWN_COMPUTER_,
    SHOW_DISTANCE_,
    CANCEL_DISTANCE_,
    READY_,
    PLAY_MUSIC_,
    PLAY__MUSIC_,
    PLAY_SONG_,
    PLAY__SONG_,
    AIR_QUALITY_,
    AIR__QUALITY_,
    SHOW_AIR_QUALITY_,
    SHOW_AIR__QUALITY_,
    WEATHER_REPORT_,
    WEATHER__REPORT_,
    THINK_,
    THINK_HARDER_,
    SPARKLE_,
    ASTERISK,
    GREATER_THAN,
    RO_,
    RW_,
    RECORD_MESSAGE_,
    PLAY_MESSAGE_,
    PLAY__MESSAGE_,
    PLAY_MESSAGES_,
    PLAY__MESSAGES_,
    PLAY_AGAIN_,
    PLAY__AGAIN_,
    SAVE_,
    DELETE_,
    STOP_,
    COUNT_MESSAGES,
    HELLO_,
    STOP_LISTENING_,
    SLEEP_,
    KEEP_MESSAGE_,
    KEEP__MESSAGE_,
    SWITCH_ALPHA_,
    SWITCH_BRAVO_,
    SWITCH_CHARLIE_,
    SWITCH_DELTA_,
    SWITCH_ECHO_,
    SWITCH_FOXTROT_,
    STATUS_ALPHA_,
    STATUS_BRAVO_,
    STATUS_CHARLIE_,
    STATUS_DELTA_,
    STATUS_ECHO_,
    STATUS_FOXTROT_,
    VOLUME_UP_,
    VOLUME__UP_,
    VOLUME_DOWN_,
    VOLUME__DOWN_,
    RESET_VOLUME_,
   END_OF_LIST
};
typedef enum PhraseID PhraseID;

PhraseID phrase_to_index(const char *phrase);
const char * index_to_phrase(PhraseID index);

#endif /* phrases_h */
